// src/components/menu/NavbarComponent.vue
<template>
    <article>
      <div class="navbar">
        <div class="navbar-menu-icon" @click="toggleMenu">☰</div>
        <div class="navbar-bold-font" @click="navigate('Home')">anasayfa</div>
        <div id="navbar-right-align">
          <div @click="navigate('about')">hakkında</div>
          <img @click="navigate('question')" :src="questionImg" class="navbar-question-icon" />
          <img @click="toggleAvatar" :src="peopleFill" class="navbar-avatar-icon" />
        </div>
      </div>
      <div v-if="isMenuOpen">
        <div id="navbar-white-bar" >
          <div @click="navigate('menuItem1')">Doktorlar</div>
          <div @click="navigate('menuItem2')">Birimler</div>
          <div @click="navigate('menuItem3')">Hastalıklardan Nasıl Korunulur?</div>
          <div @click="navigate('menuItem4')">Yapay Zeka ve Akciğer Hastalıkları</div>
          <div class="navbar-button" id="navbar-return" @click="toggleMenu">Geri Dön</div>
        </div>
        <div id="navbar-black-background"></div>
      </div>
      <div v-if="isAvatar">
        <div id="navbar-white-bar-avatar">
          <img :src="peopleFill" class="navbar-avatar-icon" id="navbar-big-avatar"/>
          <div>Buğra Burak Başer</div>
          <div id="navbar-link" @click="navigate('profile')">Profili Düzenle</div>
          <div id="navbar-avatar-buttons">
            <div class="navbar-button" id="navbar-logout" @click="navigate('logout')">Çıkış Yap</div>
            <div class="navbar-button" id="navbar-return" @click="toggleAvatar">Geri Dön</div>
          </div>
        </div>
        <div id="navbar-black-background"></div>
      </div>
    </article>
  </template>
  
  <script>
  export default {
    data: () => {
      return {
        isMenuOpen: false,
        isAvatar: false,
        questionImg: require('@/assets/questionImg.png'),
        peopleFill: require('@/assets/peopleFill.png'),

      };
    },
    methods: {
      toggleMenu() {
        this.isMenuOpen = !this.isMenuOpen;
      },
      toggleAvatar() {
        this.isAvatar = !this.isAvatar;
      },
      navigate(page) {
        console.log("Navigating to " + page);
      },
    }
  };
  </script>
  
  <style lang="scss" scoped>
  .navbar {
    position: fixed;
    margin: 0;
    padding: 0;
    top: 0px;
    left: 0px;
    width: 100%;
    height: 40px;
    background: var(--unnamed-color-ffffff) 0% 0% no-repeat padding-box; /* Provided background style */
    background: #FFFFFF 0% 0% no-repeat padding-box; /* Fallback background style */
    color: #000000;
    display: flex;
    align-items: center;
    text-align: left;
    font: normal normal normal 20px/28px 'Segoe UI';
    letter-spacing: 0px;
    box-shadow: 0px 3px 6px #00000029; 
    opacity: 1;
    z-index: 2;
  }
  
  #navbar-white-bar{
    position: fixed;
    top: 0;
    left: 0;
    width: 250px;
    height: 100%;
    background-color: #ffffff;
    box-shadow: 0px 3px 6px #00000029;
    z-index: 1 !important; /* Menü önce gelmeli */
    align-items: center;
    text-align: center;
    font: normal normal normal 20px/28px 'Segoe UI';
    color: #000000;
    letter-spacing: 0px;
    display: flex;
    flex-direction: column;
  }
  
  #navbar-white-bar div {
    width: fixed;
    height: fixed; 
    margin-top: 15px;
    margin-bottom: 5px;
    cursor: pointer;
  }
  
  
  #navbar-white-bar-avatar {
    position: fixed;
    top: 0;
    right: 0 !important;
    width: 250px;
    height: 350px;
    background-color: #ffffff;
    box-shadow: 0px 3px 6px #00000029;
    z-index: 1 !important; /* Menü önce gelmeli */
    align-items: center;
    text-align: center;
    font: normal normal normal 20px/28px 'Segoe UI';
    color: #000000;
    letter-spacing: 0px;
    display: flex;
    flex-direction: column;
  }
  
  #navbar-white-bar-avatar div {
    width: fixed;
    height: fixed; 
    margin-top: 10px;
  }
  
  #navbar-avatar-buttons {
    width: 100%;
    align-items: center;
    text-align: center;
    display: flex;
  
    cursor: default !important;
    margin-top: auto !important; /* Üst boşluk */
    margin-bottom: 0 !important; /* Alt boşluk */
  }
  
  
  #navbar-avatar-buttons div{
    width: fixed;
    height: fixed; 
    margin-top: 10px;
    cursor: pointer;
  }
  
  .navbar-button {
    width: 40%;
    background: #aec2ff; /* Arkaplan rengi */
    box-shadow: 0px 3px 6px #00000029;  /* Gölge efekti */
    border-radius: 39px; /* Kenar yuvarlaklığı */
    opacity: 1; /* Opaklık */
    cursor: pointer; /* Fare imleci */
  }
  .navbar-button:hover {
    box-shadow: inset 0px 3px 6px #00000029; /* :hover durumunda outer (dış) gölge efekti */
  }
  
  #navbar-logout {
    margin-top: auto !important; /* Üst boşluk */
    margin-bottom: 20px !important; /* Alt boşluk */
    margin-left: 20px;
    margin-right: 10px;
    background: #ffabab !important;
  
  }
  
  #navbar-return {
    margin-top: auto !important; /* Üst boşluk */
    margin-bottom: 20px !important; /* Alt boşluk */
  }
  
  
  #navbar-black-background {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-color: rgba(0, 0, 0, 0.7); /* Siyah arka plan (0.7 opaklık) */
    z-index: 0 !important; /* Arkada olmalı, menüden sonra gelecek */
  }
  
  .navbar-bold-font {
    font: normal normal bold 20px/28px 'Segoe UI';
  }
  #navbar-right-align {
    display: flex;
    margin-left: auto !important;
    margin-right: 20px !important;
    cursor: default !important;
    align-items: center;
    font: normal normal normal 20px/28px 'Segoe UI';
    color: #000000;
    letter-spacing: 0px;
  }
  
  .navbar-question-icon {
    width: 20px;
    height: 20px;
    background-size: cover;
    margin-left: 10px;
    margin-right: 10px;
    cursor: pointer;
  }
  
  .navbar-menu-icon {
    margin-left: 20px !important;
  }
  .navbar-avatar-icon {
    width: 30px;
    height: 30px; 
    border-radius: 50%; 
    background: #F8F8F8 0% 0% no-repeat padding-box;
    background-size: cover;
    margin-left: 10px;
    margin-right: 10px;
    box-shadow: inset 0px 3px 6px #00000029;
    border: 1px solid #e1e1e1;
    cursor: pointer;
  }
  
  .navbar div {
    margin-left: 10px;
    margin-right: 10px;
    cursor: pointer;
  }
  
  #navbar-big-avatar{
    margin-top: 4%;
    width: 50%;
    height: auto; 
    cursor: default;
  }
  
  
  #navbar-link{
    text-decoration: underline; /* Altı çizili stil */
    cursor: pointer;
  }
  
  </style>

// src/components/menu/NavbarComponent.tsx
import React, { useState } from 'react';
import './NavbarComponent.scss';  // Stil dosyasını ekleyin
import questionImg from '../../assets/questionImg.png';
import peopleFill from '../../assets/peopleFill.png';
import { SideSlide } from "../SideSlide";


interface NavbarComponentProps {
    isDoctor: boolean;
    isPatient: boolean;
}

const Navbar: React.FC<NavbarComponentProps> = (props) => {
    const { isDoctor, isPatient } = props;
    const [isMenuOpen, setMenuOpen] = useState(false);
    const [isAvatarOpen, setAvatarOpen] = useState(false);

    const toggleMenu = () => {
        setMenuOpen(!isMenuOpen);
    };

    const toggleAvatar = () => {
        setAvatarOpen(!isAvatarOpen);
    };

    const navigate = (page: string) => {
        console.log("Navigating to " + page);
    };

    return (
        <article>

            <div className="navbar">
                <div className="navbar-menu-icon" onClick={toggleMenu}>☰</div>
                <div className="navbar-bold-font" onClick={() => navigate('Home')}>anasayfa</div>
                {isDoctor && (
                    <>
                        <div onClick={() => navigate('hastalar')}>hastalar</div>
                        <div onClick={() => navigate('raporlar')}>raporlar</div>
                    </>
                )}
                {isPatient && (
                    <div onClick={() => navigate('raporlarım')}>raporlarım</div>
                )}
                <div id="navbar-right-align">
                    <div onClick={() => navigate('about')}>hakkında</div>
                    <img src={questionImg} alt="Question Icon" className="navbar-question-icon" />
                    <img onClick={toggleAvatar} src={peopleFill} alt="Avatar Icon" className="navbar-avatar-icon" />
                </div>
            </div>
            <SideSlide isAvatar={false} isMenu={true} isOpen={isMenuOpen}>
                <>
                    <div className='sidebar'>
                        <div id="navbar-white-bar" >
                            <div onClick={() => navigate('menuItem1')}>Doktorlar</div>
                            <div onClick={() => navigate('menuItem2')}>Birimler</div>
                            <div onClick={() => navigate('menuItem3')}>Hastalıklardan Nasıl Korunulur?</div>
                            <div onClick={() => navigate('menuItem4')}>Yapay Zeka ve Akciğer Hastalıkları</div>
                            <div className="navbar-button" id="navbar-return" onClick={toggleMenu}>Geri Dön</div>
                        </div>
                    </div>
                    <div id='navbar-black-background' onClick={toggleMenu}></div>
                </>
            </SideSlide>
            <SideSlide isAvatar={true} isMenu={false} isOpen={isAvatarOpen}>
                <>
                    <div className='sidebar'>
                        <div id="navbar-white-bar-avatar">
                            <img src={peopleFill} className="navbar-avatar-icon" id="navbar-big-avatar" alt="Big Avatar" />
                            <div>Buğra Burak Başer</div>
                            <div id="navbar-link" onClick={() => navigate('profile')}>Profili Düzenle</div>
                            <div id="navbar-avatar-buttons">
                                <div className="navbar-button" id="navbar-logout" onClick={() => navigate('logout')}>Çıkış Yap</div>
                                <div className="navbar-button" id="navbar-return" onClick={toggleAvatar}>Geri Dön</div>
                            </div>
                        </div>
                    </div>
                    <div id='navbar-black-background' onClick={toggleAvatar}></div>
                </>
            </SideSlide>
        </article>
    );
};

export default Navbar;
